Add LUKS encryption to VirtualBox-NixOS

diff --git a/iso/install-nixos-with-disko b/iso/install-nixos-with-disko
--- a/iso/install-nixos-with-disko
+++ b/iso/install-nixos-with-disko
@@ -37,11 +37,15 @@ if [[ ! -e "home-manager/dyson/sops-secrets/key.txt" ]]; then
     fi
 fi
 
-# Check if the machine we're provisioning expects a keyfile to unlock a disk.
-# If it does, generate a new key, and write to a known location.
-if grep -q "luks.keyfile" "machines/${TARGET_HOST}/disko.nix"; then
-  echo -n "$(head -c32 /dev/random | base64)" > /tmp/luks.keyfile
-fi
+password_files="$(grep -Po '(?<=passwordFile = ")[^"]+(?=";)' "machines/${TARGET_HOST}/disko.nix" | uniq)"
+
+while IFS= read -r password_file; do
+	if [[ ! -f "$password_file" ]]; then
+		echo "ERROR! ${TARGET_HOST} requires a LUKS password in ${password_file} but this file was not found"
+		echo "Please write to this file with \`echo -n \"password\" > ${password_file}\` and try again"
+		exit 1
+	fi
+done <<< "$password_files"
 
 echo "WARNING! The disks in ${TARGET_HOST} are about to get wiped"
 echo "         NixOS will be re-installed"
@@ -50,20 +54,11 @@ echo
 read -p "Are you sure? [y/N] " -n 1 -r
 echo
 if [[ $REPLY =~ ^[Yy]$ ]]; then
-    sudo true
-
     sudo DISKOCOMMAND --mode disko "machines/${TARGET_HOST}/disko.nix"
 
     # Rsync my nix-config to the target install
     sudo mkdir -p "/mnt/etc/nixos"
     sudo rsync -a --delete "/iso/config/" "/mnt/etc/nixos"
-
-    # If there is a keyfile for a data disk, put copy it to the root partition and
-    # ensure the permissions are set appropriately.
-    if [[ -f "/tmp/luks.keyfile" ]]; then
-      sudo cp /tmp/luks.keyfile /mnt/etc/luks.keyfile
-      sudo chmod 0400 /mnt/etc/luks.keyfile
-    fi
 
     sudo nixos-install --flake ".#${TARGET_HOST}"
 else
